name: Check code quality

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/docs/**'

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools and ALSA dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential libasound2-dev pkg-config;

    - name: Install Rust stable
      run: rustup install stable

    - name: Check code formatting
      run: cargo fmt --all -- --check

    - name: Run Clippy linter
      run: cargo clippy --all-targets -- -D warnings
